; PlatformIO Project Configuration File
; ESP32-CAM AI-Thinker 视频流测试

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

; 添加摄像头库依赖
lib_deps =
    esp32-camera
    mathieucarbou/ESPAsyncWebServer
    mathieucarbou/AsyncTCP

; 启用PSRAM支持
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -Iinclude
